### ISSUE TITLE
Determine TRISTAN Normalizations 

### ISSUE THREAD

**Issue by JunoRavin** [collinrbr/FPCAnalysis#3]
Right now tristanFPC.py is binning and plotting cuts of data by hand in code units. Ideally, the process could be automated by de-normalizing the TRISTAN data, or automating a unit conversion. For example, we will want to bin electron and ion data with respect to their thermal velocities, so we will need to know the electron and ion thermal velocities in code units and to pass the velocity space extents and velocity space bins in terms of these (species-dependent) thermal velocities. 

TRISTAN data comes with a param file for each output frame. Possible that all we need to do is just add reading the param file to the initialization.

**Comment by collinrbr** [comment]
Done!
